(global-set-key [f5] 'compile)
(global-set-key [f6] 'new-shell)
(global-set-key [f8] 'increment-number-at-point)
(global-set-key [f13] 'ibuffer)
(global-set-key [f19] 'my-date)
(global-set-key (kbd "M-/") 'hippie-expand)
(global-set-key (kbd "C-S-v") 'scroll-other-window)
(global-set-key (kbd "M-V") 'scroll-other-window-down)
(global-set-key (kbd "M-o") 'smart-open-line-above)
(global-set-key (kbd "C-c f") 'filename-to-kill-ring)
(global-set-key (kbd "C-c n") 'next-page)
(global-set-key (kbd "C-c p") 'prev-page)
(global-set-key (kbd "C-<") (lambda () (interactive) (insert "«")))
(global-set-key (kbd "C->") (lambda () (interactive) (insert "»")))
